// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/engine_builder.proto

package org.mozc.android.inputmethod.japanese.protobuf;

public final class ProtoEngineBuilder {
  private ProtoEngineBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EngineReloadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mozc.EngineReloadRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return Whether the filePath field is set.
     */
    boolean hasFilePath();
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The filePath.
     */
    java.lang.String getFilePath();
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return Whether the magicNumber field is set.
     */
    boolean hasMagicNumber();
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The magicNumber.
     */
    java.lang.String getMagicNumber();
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The bytes for magicNumber.
     */
    com.google.protobuf.ByteString
        getMagicNumberBytes();

    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    boolean hasPriority();
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return The priority.
     */
    int getPriority();
  }
  /**
   * Protobuf type {@code mozc.EngineReloadRequest}
   */
  public  static final class EngineReloadRequest extends
      com.google.protobuf.GeneratedMessageLite<
          EngineReloadRequest, EngineReloadRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:mozc.EngineReloadRequest)
      EngineReloadRequestOrBuilder {
    private EngineReloadRequest() {
      filePath_ = "";
      magicNumber_ = "";
    }
    private int bitField0_;
    public static final int FILE_PATH_FIELD_NUMBER = 2;
    private java.lang.String filePath_;
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return Whether the filePath field is set.
     */
    @java.lang.Override
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      return filePath_;
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(filePath_);
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @param value The filePath to set.
     */
    private void setFilePath(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      filePath_ = value;
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     */
    private void clearFilePath() {
      bitField0_ = (bitField0_ & ~0x00000001);
      filePath_ = getDefaultInstance().getFilePath();
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @param value The bytes for filePath to set.
     */
    private void setFilePathBytes(
        com.google.protobuf.ByteString value) {
      filePath_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int MAGIC_NUMBER_FIELD_NUMBER = 4;
    private java.lang.String magicNumber_;
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return Whether the magicNumber field is set.
     */
    @java.lang.Override
    public boolean hasMagicNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The magicNumber.
     */
    @java.lang.Override
    public java.lang.String getMagicNumber() {
      return magicNumber_;
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The bytes for magicNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMagicNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(magicNumber_);
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @param value The magicNumber to set.
     */
    private void setMagicNumber(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      magicNumber_ = value;
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     */
    private void clearMagicNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      magicNumber_ = getDefaultInstance().getMagicNumber();
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @param value The bytes for magicNumber to set.
     */
    private void setMagicNumberBytes(
        com.google.protobuf.ByteString value) {
      magicNumber_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    @java.lang.Override
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @param value The priority to set.
     */
    private void setPriority(int value) {
      bitField0_ |= 0x00000004;
      priority_ = value;
    }
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    private void clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000004);
      priority_ = 0;
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mozc.EngineReloadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:mozc.EngineReloadRequest)
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder {
      // Construct using org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return Whether the filePath field is set.
       */
      @java.lang.Override
      public boolean hasFilePath() {
        return instance.hasFilePath();
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return The filePath.
       */
      @java.lang.Override
      public java.lang.String getFilePath() {
        return instance.getFilePath();
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return The bytes for filePath.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        return instance.getFilePathBytes();
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          java.lang.String value) {
        copyOnWrite();
        instance.setFilePath(value);
        return this;
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        copyOnWrite();
        instance.clearFilePath();
        return this;
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFilePathBytes(value);
        return this;
      }

      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return Whether the magicNumber field is set.
       */
      @java.lang.Override
      public boolean hasMagicNumber() {
        return instance.hasMagicNumber();
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return The magicNumber.
       */
      @java.lang.Override
      public java.lang.String getMagicNumber() {
        return instance.getMagicNumber();
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return The bytes for magicNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMagicNumberBytes() {
        return instance.getMagicNumberBytes();
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @param value The magicNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setMagicNumber(value);
        return this;
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagicNumber() {
        copyOnWrite();
        instance.clearMagicNumber();
        return this;
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @param value The bytes for magicNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMagicNumberBytes(value);
        return this;
      }

      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return Whether the priority field is set.
       */
      @java.lang.Override
      public boolean hasPriority() {
        return instance.hasPriority();
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return The priority.
       */
      @java.lang.Override
      public int getPriority() {
        return instance.getPriority();
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(int value) {
        copyOnWrite();
        instance.setPriority(value);
        return this;
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        copyOnWrite();
        instance.clearPriority();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mozc.EngineReloadRequest)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "filePath_",
              "magicNumber_",
              "priority_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0002\u0005\u0003\u0000\u0000\u0001\u0002\u1508\u0000\u0004" +
                "\u1008\u0001\u0005\u1004\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest> parser = PARSER;
          if (parser == null) {
            synchronized (org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mozc.EngineReloadRequest)
    private static final org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest DEFAULT_INSTANCE;
    static {
      EngineReloadRequest defaultInstance = new EngineReloadRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        EngineReloadRequest.class, defaultInstance);
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EngineReloadRequest> PARSER;

    public static com.google.protobuf.Parser<EngineReloadRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EngineReloadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mozc.EngineReloadResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return The status.
     */
    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus();

    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return The request.
     */
    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest();
  }
  /**
   * Protobuf type {@code mozc.EngineReloadResponse}
   */
  public  static final class EngineReloadResponse extends
      com.google.protobuf.GeneratedMessageLite<
          EngineReloadResponse, EngineReloadResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:mozc.EngineReloadResponse)
      EngineReloadResponseOrBuilder {
    private EngineReloadResponse() {
    }
    /**
     * Protobuf enum {@code mozc.EngineReloadResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <pre>
       * Reload command is accepted.
       * </pre>
       *
       * <code>ACCEPTED = 0;</code>
       */
      ACCEPTED(0),
      /**
       * <pre>
       * New data is verified and ready.
       * </pre>
       *
       * <code>RELOAD_READY = 1;</code>
       */
      RELOAD_READY(1),
      /**
       * <pre>
       * Engine was replaced by a new instance.
       * </pre>
       *
       * <code>RELOADED = 2;</code>
       */
      RELOADED(2),
      /**
       * <pre>
       * Failed to start reload because another reload job is currently running.
       * </pre>
       *
       * <code>ALREADY_RUNNING = 3;</code>
       */
      ALREADY_RUNNING(3),
      /**
       * <pre>
       * Errors in data file.
       * </pre>
       *
       * <code>ENGINE_VERSION_MISMATCH = 4;</code>
       */
      ENGINE_VERSION_MISMATCH(4),
      /**
       * <code>DATA_MISSING = 5;</code>
       */
      DATA_MISSING(5),
      /**
       * <code>DATA_BROKEN = 6;</code>
       */
      DATA_BROKEN(6),
      /**
       * <pre>
       * File doesn't exist or underlying memory mapping failed.
       * </pre>
       *
       * <code>MMAP_FAILURE = 7;</code>
       */
      MMAP_FAILURE(7),
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      UNKNOWN_ERROR(9),
      ;

      /**
       * <pre>
       * Reload command is accepted.
       * </pre>
       *
       * <code>ACCEPTED = 0;</code>
       */
      public static final int ACCEPTED_VALUE = 0;
      /**
       * <pre>
       * New data is verified and ready.
       * </pre>
       *
       * <code>RELOAD_READY = 1;</code>
       */
      public static final int RELOAD_READY_VALUE = 1;
      /**
       * <pre>
       * Engine was replaced by a new instance.
       * </pre>
       *
       * <code>RELOADED = 2;</code>
       */
      public static final int RELOADED_VALUE = 2;
      /**
       * <pre>
       * Failed to start reload because another reload job is currently running.
       * </pre>
       *
       * <code>ALREADY_RUNNING = 3;</code>
       */
      public static final int ALREADY_RUNNING_VALUE = 3;
      /**
       * <pre>
       * Errors in data file.
       * </pre>
       *
       * <code>ENGINE_VERSION_MISMATCH = 4;</code>
       */
      public static final int ENGINE_VERSION_MISMATCH_VALUE = 4;
      /**
       * <code>DATA_MISSING = 5;</code>
       */
      public static final int DATA_MISSING_VALUE = 5;
      /**
       * <code>DATA_BROKEN = 6;</code>
       */
      public static final int DATA_BROKEN_VALUE = 6;
      /**
       * <pre>
       * File doesn't exist or underlying memory mapping failed.
       * </pre>
       *
       * <code>MMAP_FAILURE = 7;</code>
       */
      public static final int MMAP_FAILURE_VALUE = 7;
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      public static final int UNKNOWN_ERROR_VALUE = 9;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return ACCEPTED;
          case 1: return RELOAD_READY;
          case 2: return RELOADED;
          case 3: return ALREADY_RUNNING;
          case 4: return ENGINE_VERSION_MISMATCH;
          case 5: return DATA_MISSING;
          case 6: return DATA_BROKEN;
          case 7: return MMAP_FAILURE;
          case 9: return UNKNOWN_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              @java.lang.Override
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return StatusVerifier.INSTANCE;
      }

      private static final class StatusVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Status.forNumber(number) != null;
              }
            };

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mozc.EngineReloadResponse.Status)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus() {
      org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status result = org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.forNumber(status_);
      return result == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.ACCEPTED : result;
    }
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @param value The status to set.
     */
    private void setStatus(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status value) {
      status_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     */
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest request_;
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    @java.lang.Override
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest() {
      return request_ == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance() : request_;
    }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    private void setRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
      value.getClass();
  request_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
      value.getClass();
  if (request_ != null &&
          request_ != org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance()) {
        request_ =
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.newBuilder(request_).mergeFrom(value).buildPartial();
      } else {
        request_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    private void clearRequest() {  request_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code mozc.EngineReloadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:mozc.EngineReloadResponse)
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponseOrBuilder {
      // Construct using org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      @java.lang.Override
      public boolean hasRequest() {
        return instance.hasRequest();
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest() {
        return instance.getRequest();
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder setRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
        copyOnWrite();
        instance.setRequest(value);
        return this;
        }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder setRequest(
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder builderForValue) {
        copyOnWrite();
        instance.setRequest(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder mergeRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
        copyOnWrite();
        instance.mergeRequest(value);
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder clearRequest() {  copyOnWrite();
        instance.clearRequest();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mozc.EngineReloadResponse)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "status_",
              org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.internalGetVerifier(),
              "request_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u150c\u0000\u0002" +
                "\u1409\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse> parser = PARSER;
          if (parser == null) {
            synchronized (org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:mozc.EngineReloadResponse)
    private static final org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse DEFAULT_INSTANCE;
    static {
      EngineReloadResponse defaultInstance = new EngineReloadResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        EngineReloadResponse.class, defaultInstance);
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EngineReloadResponse> PARSER;

    public static com.google.protobuf.Parser<EngineReloadResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
